Implement Cross-Validation
Sensor-Based-Activity-Recognition/pipelines pull request #105
Opened 2023-06-08 22:24 UTC by gabrieltorresgamez

#103 

@buesst1 sorry dassi wieder dir gib zum reviewe, aber da du ja das mit de modellbranches machsch würs sich am meiste lohne wennis dir gib

2023-06-08 22:48 UTC, ghost commented
# RUN: HistGradientBoostingClassifier, 2023-06-08 22-48-25

## Hyperparameters

| Path        | Param                            | main   | workspace        |
|-------------|----------------------------------|--------|------------------|
| params.yaml | cross_validation_split.cv_splits | -      | 10               |
| params.yaml | cross_validation_split.seed      | -      | 9458             |
| params.yaml | cross_validation_split.type      | -      | cross_validation |
| params.yaml | dvclive.seed                     | 41     | 42               |

## Metrics

| Path   | Metric   | main   | workspace   | Change   |
|--------|----------|--------|-------------|----------|

## Plots

### Confusion Matrix

![Confusion Matrix](https://asset.cml.dev/90f0e862951ff3fac0ff0716e307c97baabb5397?cml=png&cache-bypass=20f7941b-1371-4908-b15b-ed0fb974e1d2)

### CV Metrics

![CV Metrics](https://asset.cml.dev/4a807dd7e20ac3656631251324dfbcd9c75b2483?cml=png&cache-bypass=df3e746c-1e05-41c5-beee-1b646875cc37)

![](https://cml.dev/watermark.png#0c88b73a95424c688e3586a3374554c8af9cc9a1 "CML watermark")

2023-06-09 06:42 UTC, buesst1 requested changes
Gud.

-> siehe comment

2023-06-09 06:42 UTC, buesst1 commented on src/train_test_split.py
> +            train, test = next(kfolds)
Wiso mit next()?

Chönnt me nid einfach folgende code verwende?

for i, (train, test) in enumerate(kfolds):
   ...

2023-06-09 07:51 UTC, gabrieltorresgamez commented on src/train_test_split.py
> +            train, test = next(kfolds)
sure man, beides gaht, hans jetzt mit enumerate ersetzt

2023-06-09 08:09 UTC, buesst1 approved these changes
purrfect

2023-06-09 08:11 UTC, merged

2023-06-09 09:43 UTC, ghost commented
# RUN: HistGradientBoostingClassifier, 2023-06-09 09-42-57

## Hyperparameters

| Path   | Param   | main   | workspace   |
|--------|---------|--------|-------------|

## Metrics

| Path   | Metric   | main   | workspace   | Change   |
|--------|----------|--------|-------------|----------|

## Plots

### Confusion Matrix

![Confusion Matrix](https://asset.cml.dev/90f0e862951ff3fac0ff0716e307c97baabb5397?cml=png&cache-bypass=e0b0b40e-e2fb-4586-800f-45e099b77c66)

### CV Metrics

![CV Metrics](https://asset.cml.dev/4a807dd7e20ac3656631251324dfbcd9c75b2483?cml=png&cache-bypass=770fa339-1387-473b-891f-4800f7fae9e7)

![](https://cml.dev/watermark.png#7df75631b307d4f3c201b8db9f5369418bf50d53 "CML watermark")