F fft filters
Sensor-Based-Activity-Recognition/pipelines pull request #28
Opened 2023-03-31 13:59 UTC by buesst1

FFT transformation and filters (band, low, high)-pass added as stages.

2023-03-31 15:17 UTC, yvokeller reviewed
siehe Kommentar

2023-03-31 15:17 UTC, yvokeller commented on src/filter_bandpass.py
> +def butt_bandpass(df:pd.DataFrame, lowcut_f:float, highcut_f:float, order:int=3):
Die 3 Filter Funktionen bitte noch auslagern nach util und da eine generische Funktion schreiben die alle drei filter unterstützt, aus den stages dann entsprechend aufrufen -> sonst haben wir drei mal den gleichen Code mit ganz wenig Unterschieden

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/22744751/229160565-0a29750e-1b44-47f4-aeec-751aa350bcfa.png">

2023-03-31 16:34 UTC, buesst1 commented on src/filter_bandpass.py
> +def butt_bandpass(df:pd.DataFrame, lowcut_f:float, highcut_f:float, order:int=3):
fixed

2023-04-01 19:47 UTC, yvokeller approved these changes

2023-04-02 10:21 UTC, florinbarbisch requested changes
Can you merge the four filter files into one?

2023-04-02 10:21 UTC, florinbarbisch commented on src/filter_highpass.py
> +from utils.filters import butt_filter
butt=🍑

2023-04-02 10:21 UTC, florinbarbisch commented on src/filter_lowpass.py
3 mal gleicher code? kann das nicht in einer datei zusammengefasst werden (mit einem argument für lowpass/highpass). Less files => less maintenance => more time for meetings.

2023-04-02 10:21 UTC, florinbarbisch commented on src/utils/filters.py
> +def butt_filter(df:pd.DataFrame, filter_type:str, cutoff_freq:Union[float, Tuple[float, float]], order:int=3):
Gute Typendefinition👍🏻

2023-04-02 21:01 UTC, florinbarbisch requested changes
Ich bin immernoch der Meinung, dass wir die drei (resp. vier) Dateien in eine zusammenfügen können: 
![image](https://user-images.githubusercontent.com/40719099/229378795-0928e805-bc24-44b1-bd0a-ed3c58c1cb81.png)

2023-04-03 05:40 UTC, buesst1 commented on src/filter_lowpass.py
Sorry hab die Request nicht gesehen...

Hatte am Anfang geplant alles in ein File zu machen, 
allerdings hat der Bandpass ein Parameter mehr als die anderen Filter.

Momentan habe ich das Output file nach der Filterart benannt, damit man alleine am output File die Filterart erkennen kann. 
Wäre alles in einem File, hätte dieses drei verschiedene mögliche Outputs.
Weiss deshalb nicht, ob da DVC mit klar kommt.

2023-04-03 15:52 UTC, florinbarbisch commented on src/filter_lowpass.py
![image](https://user-images.githubusercontent.com/40719099/229562379-a266e89e-8705-4520-8abe-97eba504fd3b.png)
liesse sich lösen indem du das output file auch als sys.argv mitgibts wie in #32

2023-04-05 20:32 UTC, florinbarbisch requested changes
`dvc.yaml` und dateiname `filters.py` (siehe Kommentar für mehr Details)

2023-04-05 20:32 UTC, florinbarbisch commented on dvc.yaml
> +    params:
Ich meinte du müsstest den ganzen Pfad angben (mit filters): `filters.bandpass.lowcut_f_Hz`.

Und dann kannst du auch gleich alle params von bandpass angeben indem du nur `filters.bandpass` angibst.

2023-04-05 20:32 UTC, florinbarbisch commented on params.yaml
> +filters:
finde ich gut strukturiert!

2023-04-05 20:32 UTC, florinbarbisch commented on src/filter.py
> +from utils.filters import butterworth_filter
Ich finde den Namen der Datei noch zu wenig sprechend. `filter.py` könnte sich auch mit der Datenqualität auseinander setzen. Eine gute Lösung fände ich `butterworth_filter.py`

2023-04-06 07:35 UTC, florinbarbisch approved these changes
Nice work!

2023-04-06 08:21 UTC, merged