add scalers
Sensor-Based-Activity-Recognition/pipelines pull request #29
Opened 2023-04-01 16:35 UTC by gabrieltorresgamez

bismillah han beides ih einem commit gmacht
dvc pipeline ish au uufgsetzt, grunned und pushed

2023-04-01 16:36 UTC, gabrieltorresgamez commented
Issues #23 and #24

2023-04-12 10:48 UTC, buesst1 requested changes
Soweit alles gut.
Output filenames würde ich allerdings über Parameter mitgeben.

2023-04-19 18:22 UTC, buesst1 approved these changes

2023-04-19 19:17 UTC, gabrieltorresgamez commented
@buesst1 meinst du die parameter wie in issue #39 ?

2023-04-19 20:01 UTC, buesst1 commented
Ja genau.
Werde ich ansonsten später noch machen.
Deshalb approved👍🏻

2023-04-20 06:54 UTC, merged