Added: aggregation stage
Sensor-Based-Activity-Recognition/pipelines pull request #33
Opened 2023-04-03 15:54 UTC by florinbarbisch

2023-04-05 12:13 UTC, buesst1 requested changes

2023-04-05 12:13 UTC, buesst1 commented on src/aggregate.py
> +    with open(input_filename, "rb") as fr:
Es ist möglich, dass das neu erstellte File nach dem Verlassen des 'with' Blockes noch nicht komplett geschlossen ist.
Ansonnsten gibt es ein Fehler wenn eine andere Stage versucht auf das noch offene File zuzugreifen, was zu einer Exception führt.
Füge deshalb am Schluss des Scriptes noch ein delay von 1s oder so ein.

2023-04-05 20:41 UTC, florinbarbisch commented on src/aggregate.py
> +    with open(input_filename, "rb") as fr:
lol ha bis jetzt no kei problem gha und dönt mega komisch. Hesch das selber mol erlebt und chasch mir irgendwie en source ahgäh? Würds problem drum gern no eleganter löse😅

2023-04-06 09:32 UTC, buesst1 approved these changes

2023-04-06 09:51 UTC, merged